version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: antd
    versions:
    - 4.11.2
    - 4.12.0
    - 4.12.2
    - 4.12.3
    - 4.13.0
    - 4.13.1
    - 4.14.0
    - 4.14.1
    - 4.15.0
    - 4.15.1
    - 4.15.2
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: victory
    versions:
    - 35.4.10
    - 35.4.11
    - 35.4.12
    - 35.4.13
    - 35.4.7
    - 35.4.8
    - 35.4.9
    - 35.5.0
  - dependency-name: flow-bin
    versions:
    - 0.143.1
    - 0.144.0
    - 0.145.0
    - 0.146.0
    - 0.147.0
    - 0.148.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
  - dependency-name: react-redux
    versions:
    - 7.2.2
    - 7.2.3
