version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "12"

    volumes:
      - ..:/workspace:cached

    network_mode: host
    
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
